# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# Check on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 1.5.22
maven_group = moreberries
archives_base_name = moreberries

# Dependencies
fabric_api_version=0.152.1+26.2
cloth_version=26.1.154
