# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# Check on https://fabricmc.net/develop/
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version = 1.5.21
maven_group = moreberries
archives_base_name = moreberries

# Dependencies
fabric_api_version=0.144.3+26.1
cloth_version=26.1.154
