# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# Check on https://fabricmc.net/develop/
minecraft_version=26.3-rc-2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 1.5.23
maven_group = moreberries
archives_base_name = moreberries

# Dependencies
fabric_api_version=0.160.4+26.3
cloth_version=26.2.155
